# dependabot.yml file with version updates

version: 2
registries:
  bit-components:
    type: npm-registry
    url: https://node-registry.bit.cloud
updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - bit-components
    schedule:
      interval: "daily"
